"""
Sends the agent's recommendations via email.
Calls an AWS Lambda function URL (which triggers SES) so this module
stays free of direct SES credentials — Lambda handles that.
"""

import json
import requests


def send_recommendations(
    lambda_url: str,
    recipient: str,
    sender: str,
    subject: str,
    body: str,
) -> dict:
    """
    POST the email payload to a Lambda function URL.
    Returns the Lambda response as a dict.

    The Lambda is expected to accept JSON with keys:
      to, from, subject, body
    and return {"status": "ok"} on success.
    """
    payload = {
        "to": recipient,
        "from": sender,
        "subject": subject,
        "body": body,
    }
    response = requests.post(
        lambda_url,
        json=payload,
        headers={"Content-Type": "application/json"},
        timeout=15,
    )
    response.raise_for_status()
    return response.json()


def format_email_body(site_url: str, recommendations: str) -> str:
    """Wrap the agent's raw recommendations in a simple email template."""
    return (
        f"Website Insights Report\n"
        f"Site: {site_url}\n"
        f"{'=' * 60}\n\n"
        f"{recommendations}\n\n"
        f"{'=' * 60}\n"
        f"Generated by Website Insights Agent\n"
    )
